spring.application.name: gateway-service-zuul
server.port: 5002

#这里的配置表示，访问/it/** 直接重定向到https://m.cnblogs.com/**
zuul.routes.baidu.path: /it/**
zuul.routes.baidu.url: https://m.cnblogs.com/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/

management.endpoints.web.exposure.include: routes,filters
management.security.enabled: false