server:
  port: 8001
spring:
  application:
    name: config-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xzs603/springcloud-demos/
          search-paths: config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/